/*EXEMPLO PROFESSOR
alert("pagina1")

function lerFormulario() {
    let formulario = document.querySelectorAll("input") variavel formulario criada / query pelo seletor input
    let espaco = document.getElementById("espaco")

    espaco.innerHTML = `Nome: ${formulario[0].value}
                        Idade: ${formulario[1].value}
                        Data de Nascimento: ${formulario[2].value}`

}*/
